[package]
name = "fnv"
version = "1.0.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
description = "Fowler–Noll–Vo hash function"
license = "Apache-2 / MIT"
readme = "README.md"

[lib]
name = "fnv"
path = "lib.rs"
doctest = false
