[package]
name = "fnv"
version = "1.0.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
description = "Fowler–Noll–Vo hash function"
license = "Apache-2.0 / MIT"
readme = "README.md"
repository = "https://github.com/servo/rust-fnv"

[lib]
name = "fnv"
path = "lib.rs"
doctest = false
